### ISSUE TITLE
PDF Rasterizer workflow location need to work with 64/65 repository restructuring

### ISSUE THREAD

**Issue by JiangLong2019** [AdobeDocs/experience-manager-65.en#221] opened 2021-02-23 00:33 UTC
Recently the PDF Rasterizer feature helped me a lot in a customer project. But I found some code/configuration locations that still keep the same with old versions, such as workflow model locates under /etc. From AEM 64/65, we have to follow the repository restructuring guideline[0] to re-build node structure, or I think it will bring some troubles on upgrading in the future. Hope this can be improved very soon.

[0] - https://adobe.ly/2ZIXdAF

**Comment by aheim0** [comment] 2021-02-23 05:12
@JiangLong2019 

Thank you for your comment. 

Can I check - do you have any issues with the document itself, or are your concerns solely with the procedure?

Best regards.

**Comment by JiangLong2019** [comment] 2021-02-23 06:46
Hi @aheim0 , I don't have any concerns about documentation but the functionality. As I wrote, the location of workflow node should follow AEM 64/65 repository restructuring guideline. I'm not sure if here is the correct place to raise this, please let me know where to request function improvement.

**Comment by aheim0** [comment] 2021-02-23 06:51
@JiangLong2019 
Many thanks for getting back to us.
As the issue is not with the documentation itself we cannot help. The best approach would be to contact Support to check the situation and request future improvements.
Hope that helps - will close this issue.

**Closed by aheim0** 2021-02-23 06:51 UTC
