### ISSUE TITLE
Outdated information

### ISSUE THREAD

**Issue by gillesmetz** [AdobeDocs/experience-manager-65.en#81] opened 2020-05-25 14:48 UTC
Issue in help/sites-deploying/update-release-vehicle-definitions.md

The page https://docs.adobe.com/content/help/en/experience-manager-65/deploying/deploying/update-release-vehicle-definitions.html mentions "Hotfix" as release vehicle, but in reality we do not deliver any hotfix anymore, but interim Cumulative Fix Pack or interim Service Pack instead. 

Same of the Oak CFP release vehicle.

**Comment by anujkapo** [comment] 2020-05-25 14:51
Thanks, Gilles for reporting the issue. I'll get it fixed.

**Comment by anujkapo** [comment] 2020-06-05 12:00
CQDOC-16198

**Comment by anujkapo** [comment] 2020-06-05 13:56
The issue is resolved with the following git commit:
https://git.corp.adobe.com/AdobeDocs/experience-manager-65.en/pull/659/commits/6a5a8e64c6eaab816d07d8206601849c974d1e26

**Closed by anujkapo** 2020-06-05 13:56 UTC
Labels: error
