### ISSUE TITLE
AEMaaCS: The first time Page Help Wizard links to AEM 6.5 docs?

### ISSUE THREAD

**Issue by pzrq** [AdobeDocs/experience-manager-65.en#477] opened 2024-02-13 01:19 UTC
Issue likely in ./help/sites-authoring/first-steps.md

---

## Context/Setup

After deploying a new [AEMaaCS](https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/overview/introduction.html?lang=en) Sites Project into a sandbox, I navigated to the AEM Author > Sites > My Project > us > en > Create button dropdown > Page option. Then I chose the "Content Page" option > Next button > Fill in a title > Create button > Open button.

The first time, or later via the Actions icon dropdown > Help option, this brings up a 5 step modal page help wizard. The final step of this wizard, titled `Learn More?` has text "Check the [documentation](https://www.adobe.com/go/aem6_5_docs_page_authoring_en)."

![Screenshot from 2024-02-13 12-11-53](https://github.com/AdobeDocs/experience-manager-65.en/assets/1217010/433f4f3f-c0cf-4b68-b665-203ab73d4a33)

https://www.adobe.com/go/aem6_5_docs_page_authoring_en currently links through to https://experienceleague.adobe.com/docs/experience-manager-65/content/sites/authoring/essentials/first-steps.html which I clicked "Detailed Feedback Options" at the bottom of the page on.

## Question
My question is - does this page apply for both AEM as a Cloud Service, or just AEM 6.5?

## Expected
I'd expect both authoring workflows - AEM 6.5 and AEMaaCS to be quite similar, though it'd be good to know in case of any subtle differences which may have occurred over time, or if there's already an AEMaaCS authoring page I have not found yet, and if so, perhaps, that wizard link should be updated accordingly.

**Comment by aheim0** [comment] 2024-02-13 05:43
Thank you for raising this. 

You are correct. There are strong similarities between both versions, and although the overview page you've indicated is generally applicable to both, it references further pages where the differences might be more significant.

For AEMaaCS I'd suggest starting with the following if you're interested in page authoring. It is also an overview page, but it references the relevant pages if you want more detail:

- https://experienceleague.adobe.com/docs/experience-manager-cloud-service/content/sites/authoring/getting-started/quick-start.html

And again, you are correct - the issue seems to be caused by an out-of-date link in the wizard. We will notify the appropriate group, so that the matter can be corrected. As this is outside our control I'll close this issue now - but feel free to contact us if you have anymore questions about the documentation. Thanks for your help.

**Comment by aheim0** [comment] 2024-02-13 05:43
@adobe export issue to Jira project CQDOC

**Closed** 2024-02-13 05:44 UTC
Labels: Bug, Tracked
