### ISSUE TITLE
Clarify the troubleshooting steps for "Modify Operation Exception During Response Processing"

### ISSUE THREAD

**Issue by clatimier** [AdobeDocs/experience-manager-65.en#149] opened 2020-08-25 10:17 UTC
Issue in help/sites-administering/sync.md

In the documentation (1) it is mentioned that in case of exception "org.apache.sling.servlets.post.impl.operations.ModifyOperation Exception during response processing.
java.lang.IllegalStateException: This tree does not exist" the step 2 needed to be verified
However, in the step 3 it is mentioned to check the credentials in "Apache Sling Distribution Transport Credentials - User Credentials based DistributionTransportSecretProvider" only where the configuration will also exist in "com.adobe.granite.distribution.core.impl.CryptoDistributionTransportSecretProvider.name" 
This needs to be clarify in the "Troubleshooting" part (1)

https://docs.adobe.com/content/help/en/experience-manager-65/administering/security/sync.html#modify-operation-exception-during-response-processing

[Logged by Support]

**Comment by aheim0** [comment] 2020-08-31 03:14
Thanks for highlighting this, we will investigate.

**Comment by aheim0** [comment] 2020-08-31 03:25
Being tracked with CQDOC-16741.

**Comment by sarchiz** [comment] 2021-02-03 11:54
Closing, as this is a duplicate of https://github.com/AdobeDocs/experience-manager-64.en/issues/109

If an issue is applicable to both on-prem documentation sets, open it in only one (preferably 6.5) and mention that it needs to be backported as well. Thanks.

**Closed by sarchiz** 2021-02-03 11:54 UTC
Labels: enhancement
